"""修改了对于执行方案的命名错误

Revision ID: 38ead194b463
Revises: a4df5e634e7f
Create Date: 2024-01-20 12:15:13.426157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ead194b463'
down_revision: Union[str, None] = 'a4df5e634e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers_sign_up', sa.Column('executionPlanPath', sa.String(), nullable=True))
    op.drop_column('volunteers_sign_up', 'personalExpectationsPath')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers_sign_up', sa.Column('personalExpectationsPath', sa.VARCHAR(), nullable=True))
    op.drop_column('volunteers_sign_up', 'executionPlanPath')
    # ### end Alembic commands ###
