"""Create volunteers_initiate table

Revision ID: 5684496a0e34
Revises: 62d52d8a1acd
Create Date: 2024-01-17 20:12:11.062616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5684496a0e34'
down_revision: Union[str, None] = '62d52d8a1acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
