"""新增了个人图片、简历、执行方案的系统文件路径

Revision ID: a4df5e634e7f
Revises: b7409a7a3d34
Create Date: 2024-01-20 12:11:31.801866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4df5e634e7f'
down_revision: Union[str, None] = 'b7409a7a3d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers_sign_up', sa.Column('resumePath', sa.String(), nullable=True))
    op.add_column('volunteers_sign_up', sa.Column('personalExpectationsPath', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers_sign_up', 'personalExpectationsPath')
    op.drop_column('volunteers_sign_up', 'resumePath')
    # ### end Alembic commands ###
