"""新增了个人图片、简历、执行方案的系统文件路径

Revision ID: b7409a7a3d34
Revises: 5684496a0e34
Create Date: 2024-01-20 12:10:22.433360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7409a7a3d34'
down_revision: Union[str, None] = '5684496a0e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
