"""修改了对于执行方案的命名错误

Revision ID: ecc4c3075a3a
Revises: 38ead194b463
Create Date: 2024-01-20 12:15:22.145871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc4c3075a3a'
down_revision: Union[str, None] = '38ead194b463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
